### PR TITLE
Added support to pass spawn options

### PR DESCRIPTION
**Pull request by shaharkazaz**
Also:
* Convert js to TS and added types
* Added protection in case no args are passed

### CODE REVIEW

**Comment by pankajladhar** [comment]
@shaharkazaz Thanks for pull request. I will look into this.

**Comment by shaharkazaz** [comment]
Any updates?

**Comment by pankajladhar** [comment]
I had gone through your pull request. Could you please tell while running `git command` what spawn options user could pass ?

**Comment by shaharkazaz** [comment]
I have added the interface 'SpawnOptions', but you can also see the options that the spawn supports in the [child_process.spawn documentation](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)

**Comment by pankajladhar** [comment]
I have gone through child_process.spawn documentation. But if you see run-git-command is very specific to run git command. I don't this spawn options is required.

If you run any other command as documentation says you might need spawn options.

If you could gimme some example where while running git command you need spawn options. will be helpful to understand.

**Comment by shaharkazaz** [comment]
I needed cwd property set for example, the script wasn't running from the git location.
maybe I can limit the options to support only the options we want

**Comment by pankajladhar** [comment]
node [cmd](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows) options which is not applicable, because I have hard coded `git` as first arg.

Converting into TypeScript is fine for me. 

` I can limit the options to support only the options we want` what will be those options ?

**Comment by shaharkazaz** [comment]
I'm sorry I didn't understand this: 
> node cmd options which is not applicable, because I have hard coded git as first arg.

The spawn is working with both "git" as hard coded command, the git args and the spawn options.
as for limiting the options, If you want we can support only cwd for now and update in the future if needed.

**Comment by pankajladhar** [comment]
I think its fine. I will merge it. 
One favor, if you have some bandwidth can you write unit test for this. 

Could you please update readme.md with spawn options ?

**Comment by shaharkazaz** [comment]
I will update the README file, not sure I will have time for writing unittests, at least not in the short run

**Comment by pankajladhar** [comment]
Once you update lemme know. I will merge pull request as well I will release it.

**Comment by shaharkazaz** [comment]
I have updated the README file, tell me what you think.
If we go with my suggested version you need to create a wiki page for the executor options, I can't add it since I don't have any permissions in this repo.

**Comment by shaharkazaz** [comment]
Are you merging the PR?

**Comment by pankajladhar** [comment]
I have facing some problem while publishing. Since we are converting our code to ES6 from TS.
I will see into that.

**Comment by shaharkazaz** [comment]
You need to publish only the compiled js, let me know if you need any help

**Comment by shaharkazaz** [comment]
Also, don't forget to create a wiki page for the executor options and link it in the README file 🙂

**Comment by shaharkazaz** [comment]
@pankajladhar I see you haven't published this yet

**Comment by pankajladhar** [comment]
I published it.

**Pull request merged**
